const DISCLAIMER_ACCEPTANCE_KEY = 'disclaimer_accepted';
const DISCLAIMER_VERSION_KEY = 'disclaimer_version';
const CURRENT_DISCLAIMER_VERSION = '1.0';

/**
 * Disclaimer acceptance service for tracking user agreement to terms.
 * Stores acceptance in localStorage with version tracking.
 */
class DisclaimerService {
  /**
   * Check if user has accepted the current disclaimer version.
   *
   * @returns True if current disclaimer version is accepted
   */
  hasAccepted(): boolean {
    const accepted = localStorage.getItem(DISCLAIMER_ACCEPTANCE_KEY);
    const version = localStorage.getItem(DISCLAIMER_VERSION_KEY);

    return accepted === 'true' && version === CURRENT_DISCLAIMER_VERSION;
  }

  /**
   * Mark disclaimer as accepted for current version.
   */
  accept(): void {
    localStorage.setItem(DISCLAIMER_ACCEPTANCE_KEY, 'true');
    localStorage.setItem(DISCLAIMER_VERSION_KEY, CURRENT_DISCLAIMER_VERSION);
  }

  /**
   * Clear disclaimer acceptance (for testing or logout).
   */
  clear(): void {
    localStorage.removeItem(DISCLAIMER_ACCEPTANCE_KEY);
    localStorage.removeItem(DISCLAIMER_VERSION_KEY);
  }

  /**
   * Get current disclaimer version.
   *
   * @returns Current disclaimer version
   */
  getCurrentVersion(): string {
    return CURRENT_DISCLAIMER_VERSION;
  }

  /**
   * Get accepted disclaimer version.
   *
   * @returns Accepted version or null if not accepted
   */
  getAcceptedVersion(): string | null {
    return localStorage.getItem(DISCLAIMER_VERSION_KEY);
  }

  /**
   * Get disclaimer text.
   *
   * @returns Disclaimer text
   */
  getDisclaimerText(): string {
    return `
IMPORTANT DISCLAIMER

This portfolio recommendation tool is provided for informational and educational purposes only.
By using this tool, you acknowledge and agree to the following:

1. NOT FINANCIAL ADVICE
   The recommendations, analyses, and insights provided by this tool do NOT constitute
   financial, investment, legal, or tax advice. They are based on quantitative models and
   historical data analysis.

2. NO GUARANTEE OF RESULTS
   Past performance does not guarantee future results. The stock market involves risk,
   including the potential loss of principal. Factor-based strategies may underperform
   during certain market conditions.

3. YOUR RESPONSIBILITY
   You are solely responsible for your investment decisions. Before making any investment,
   you should:
   - Conduct your own research and due diligence
   - Consider your personal financial situation, risk tolerance, and investment objectives
   - Consult with a qualified financial advisor, accountant, or attorney

4. MODEL LIMITATIONS
   The recommendations are generated by quantitative models that:
   - May contain errors, bugs, or limitations
   - Rely on historical data that may not predict future performance
   - May not account for all market conditions, risks, or factors
   - Are subject to data quality and timeliness constraints

5. NO WARRANTIES
   This tool is provided "AS IS" without warranties of any kind, either express or implied,
   including but not limited to accuracy, completeness, reliability, or fitness for a
   particular purpose.

6. LIMITATION OF LIABILITY
   The creators, operators, and contributors of this tool shall not be liable for any
   direct, indirect, incidental, consequential, or punitive damages arising from your
   use of this tool or reliance on its recommendations.

7. REGULATORY COMPLIANCE
   This tool is not registered as an investment advisor with any regulatory authority.
   It does not provide personalized investment advice tailored to your specific circumstances.

By clicking "I Accept" below, you confirm that you have read, understood, and agree to
this disclaimer and its terms.
    `.trim();
  }
}

export const disclaimerService = new DisclaimerService();
